# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1326, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1290, 702))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.doubleSpinBoxR = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxR.setMinimumSize(QtCore.QSize(100, 30))
        self.doubleSpinBoxR.setObjectName("doubleSpinBoxR")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxR)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBoxk = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxk.setMinimumSize(QtCore.QSize(100, 30))
        self.doubleSpinBoxk.setObjectName("doubleSpinBoxk")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxk)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBoxC = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxC.setMinimumSize(QtCore.QSize(100, 30))
        self.doubleSpinBoxC.setObjectName("doubleSpinBoxC")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxC)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.doubleSpinBoxT = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBoxT.setMinimumSize(QtCore.QSize(100, 30))
        self.doubleSpinBoxT.setMaximum(10.0)
        self.doubleSpinBoxT.setObjectName("doubleSpinBoxT")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxT)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBoxI = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxI.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBoxI.setMaximum(10000)
        self.spinBoxI.setObjectName("spinBoxI")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxI)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBoxK = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBoxK.setMinimumSize(QtCore.QSize(100, 30))
        self.spinBoxK.setMaximum(10000)
        self.spinBoxK.setObjectName("spinBoxK")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBoxK)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.resultch = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultch.setFont(font)
        self.resultch.setText("")
        self.resultch.setObjectName("resultch")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.resultch)
        self.resultanal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resultanal.setFont(font)
        self.resultanal.setText("")
        self.resultanal.setObjectName("resultanal")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.resultanal)
        self.verticalLayout.addLayout(self.formLayout)
        self.result = QtWidgets.QLabel(self.layoutWidget)
        self.result.setText("")
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 30))
        self.pushButton.setSizeIncrement(QtCore.QSize(10, 10))
        self.pushButton.setBaseSize(QtCore.QSize(10, 10))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView = PlotWidget(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.graphicsView.plotItem.setLabel(axis='left', text="u(θ,t)")
        self.graphicsView.plotItem.showGrid(x=True, y=True)
        self.graphicsView.plotItem.setLabel(axis='bottom', text="θ")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1326, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Радиус, R "))
        self.label_2.setText(_translate("MainWindow", "Коэффициент теплопроводности, k"))
        self.label_3.setText(_translate("MainWindow", "Коэффициент объёмной теплоёмкости, с"))
        self.label_4.setText(_translate("MainWindow", "Временной промежуток 0 < t < T, t"))
        self.label_5.setText(_translate("MainWindow", "Параметр сетки по θ, I"))
        self.label_6.setText(_translate("MainWindow", "Параметр сетки по t, K"))
        self.label_7.setText(_translate("MainWindow", "Численое решение"))
        self.label_8.setText(_translate("MainWindow", "Аналитическое решение"))
        self.pushButton.setText(_translate("MainWindow", "Построить график"))
from pyqtgraph import PlotWidget
